# Generated by Django 6.0.5 on 2026-06-03 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-friendly template name.', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The source document this template is based on.', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
