# Generated by Django 6.0.5 on 2026-05-24 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('document.uploaded', 'Document Uploaded'), ('package.created', 'Package Created'), ('package.sent', 'Package Sent'), ('signing.viewed', 'Signing Link Viewed'), ('signing.signed', 'Document Signed'), ('package.completed', 'Package Completed'), ('package.expired', 'Package Expired'), ('package.declined', 'Package Declined')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='packages.package')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='packages.recipient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
