# Generated by Django 6.0.5 on 2026-05-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('packages', '0003_package_signed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='packages.package'),
        ),
    ]
