# Generated by Django 6.0.5 on 2026-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('document.uploaded', 'Document Uploaded'), ('package.created', 'Package Created'), ('package.sent', 'Package Sent'), ('signing.viewed', 'Signing Link Viewed'), ('signing.signed', 'Document Signed'), ('package.completed', 'Package Completed'), ('package.expired', 'Package Expired'), ('package.declined', 'Package Declined'), ('package.cancelled', 'Package Cancelled')], max_length=50),
        ),
    ]
