# Generated by Django 6.0.5 on 2026-06-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_add_reminder_audit_events'),
        ('packages', '0005_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='packages.package'),
        ),
    ]
