# Generated by Django 6.0.5 on 2026-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_make_audit_immutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('document.uploaded', 'Document Uploaded'), ('package.created', 'Package Created'), ('package.sent', 'Package Sent'), ('signing.viewed', 'Signing Link Viewed'), ('signing.signed', 'Document Signed'), ('package.completed', 'Package Completed'), ('package.expired', 'Package Expired'), ('package.declined', 'Package Declined'), ('package.cancelled', 'Package Cancelled'), ('reminder.sent', 'Reminder Sent'), ('link.resent', 'Link Resent'), ('signing.approved', 'Document Approved'), ('signing.returned', 'Document Returned for Rework'), ('recipient.delegated', 'Signing Delegated'), ('package.returned', 'Package Returned'), ('package.resent', 'Package Resent')], max_length=50),
        ),
    ]
