# documents/pdf_utils.py

import io
import base64
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from pypdf import PdfReader, PdfWriter
from PIL import Image


def generate_signature_certificate(package, recipients_data):
    """
    Generates a signature certificate page as a PDF bytes object.
    recipients_data: list of dicts with name, email, signed_at,
                     ip_address, signature_data
    """
    buffer = io.BytesIO()
    page_width, page_height = A4
    c = canvas.Canvas(buffer, pagesize=A4)

    # Header
    c.setFillColor(colors.HexColor('#2563eb'))
    c.rect(0, page_height - 60*mm, page_width, 60*mm, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 20)
    c.drawString(20*mm, page_height - 25*mm, 'Certificate of Completion')

    c.setFont('Helvetica', 11)
    c.drawString(20*mm, page_height - 38*mm, f'Document: {package.document.original_filename}')
    c.drawString(20*mm, page_height - 47*mm, f'Subject: {package.subject}')

    # Body
    y = page_height - 75*mm
    c.setFillColor(colors.black)
    c.setFont('Helvetica-Bold', 13)
    c.drawString(20*mm, y, 'Signatures')
    y -= 8*mm

    c.setStrokeColor(colors.HexColor('#e5e7eb'))
    c.line(20*mm, y, page_width - 20*mm, y)
    y -= 8*mm

    for i, r in enumerate(recipients_data):
        if y < 60*mm:
            c.showPage()
            y = page_height - 20*mm

        # Signer info
        c.setFont('Helvetica-Bold', 11)
        c.setFillColor(colors.black)
        c.drawString(20*mm, y, r['name'])
        y -= 6*mm

        c.setFont('Helvetica', 9)
        c.setFillColor(colors.HexColor('#6b7280'))
        c.drawString(20*mm, y, f"Email: {r['email']}")
        y -= 5*mm
        c.drawString(20*mm, y, f"Signed: {r['signed_at']}")
        y -= 5*mm
        if r.get('ip_address'):
            c.drawString(20*mm, y, f"IP Address: {r['ip_address']}")
            y -= 5*mm

        # Signature image
        if r.get('signature_data'):
            try:
                # Decode base64 signature
                img_data = r['signature_data'].split(',')[1]
                img_bytes = base64.b64decode(img_data)
                img = Image.open(io.BytesIO(img_bytes))

                img_buffer = io.BytesIO()
                img.save(img_buffer, format='PNG')
                img_buffer.seek(0)

                sig_width = 60*mm
                sig_height = 20*mm

                c.drawImage(
                    img_buffer,
                    20*mm, y - sig_height,
                    width=sig_width,
                    height=sig_height,
                    preserveAspectRatio=True,
                    mask='auto'
                )
                y -= sig_height + 3*mm
            except Exception:
                c.drawString(20*mm, y, '[Signature image unavailable]')
                y -= 5*mm

        # Divider between signers
        c.setStrokeColor(colors.HexColor('#e5e7eb'))
        c.line(20*mm, y - 3*mm, page_width - 20*mm, y - 3*mm)
        y -= 10*mm

    # Footer
    c.setFont('Helvetica', 8)
    c.setFillColor(colors.HexColor('#9ca3af'))
    c.drawString(
        20*mm, 15*mm,
        f'Generated by eSign Platform · {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC'
    )

    c.save()
    buffer.seek(0)
    return buffer


def merge_pdf_with_certificate(original_file, certificate_buffer):
    """
    Appends the certificate page to the original PDF.
    Returns bytes of the merged PDF.
    """
    writer = PdfWriter()

    # Add all original pages
    reader = PdfReader(original_file)
    for page in reader.pages:
        writer.add_page(page)

    # Add certificate page
    cert_reader = PdfReader(certificate_buffer)
    for page in cert_reader.pages:
        writer.add_page(page)

    output = io.BytesIO()
    writer.write(output)
    output.seek(0)
    return output