# documents/pdf_utils.py

import io
import base64
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from pypdf import PdfReader, PdfWriter
from PIL import Image


def generate_signature_certificate(package, recipients_data):
    """
    Generates a signature certificate page as a PDF bytes object.
    recipients_data: list of dicts with name, email, signed_at,
                     ip_address, signature_data
    """
    buffer = io.BytesIO()
    page_width, page_height = A4
    c = canvas.Canvas(buffer, pagesize=A4)

    # Header
    c.setFillColor(colors.HexColor('#2563eb'))
    c.rect(0, page_height - 60*mm, page_width, 60*mm, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 20)
    c.drawString(20*mm, page_height - 25*mm, 'Certificate of Completion')

    c.setFont('Helvetica', 11)
    c.drawString(20*mm, page_height - 38*mm, f'Document: {package.document.original_filename}')
    c.drawString(20*mm, page_height - 47*mm, f'Subject: {package.subject}')

    # Body
    y = page_height - 75*mm
    c.setFillColor(colors.black)
    c.setFont('Helvetica-Bold', 13)
    c.drawString(20*mm, y, 'Signatures')
    y -= 8*mm

    c.setStrokeColor(colors.HexColor('#e5e7eb'))
    c.line(20*mm, y, page_width - 20*mm, y)
    y -= 8*mm

    for i, r in enumerate(recipients_data):
        if y < 60*mm:
            c.showPage()
            y = page_height - 20*mm

        # Signer info
        c.setFont('Helvetica-Bold', 11)
        c.setFillColor(colors.black)
        c.drawString(20*mm, y, r['name'])
        y -= 6*mm

        c.setFont('Helvetica', 9)
        c.setFillColor(colors.HexColor('#6b7280'))
        c.drawString(20*mm, y, f"Email: {r['email']}")
        y -= 5*mm
        c.drawString(20*mm, y, f"Signed: {r['signed_at']}")
        y -= 5*mm
        if r.get('ip_address'):
            c.drawString(20*mm, y, f"IP Address: {r['ip_address']}")
            y -= 5*mm

        # Signature image
        if r.get('signature_data'):
            try:
                # Decode base64 signature
                img_data = r['signature_data'].split(',')[1]
                img_bytes = base64.b64decode(img_data)
                img = Image.open(io.BytesIO(img_bytes))

                img_buffer = io.BytesIO()
                img.save(img_buffer, format='PNG')
                img_buffer.seek(0)

                sig_width = 60*mm
                sig_height = 20*mm

                c.drawImage(
                    img_buffer,
                    20*mm, y - sig_height,
                    width=sig_width,
                    height=sig_height,
                    preserveAspectRatio=True,
                    mask='auto'
                )
                y -= sig_height + 3*mm
            except Exception:
                c.drawString(20*mm, y, '[Signature image unavailable]')
                y -= 5*mm

        # Divider between signers
        c.setStrokeColor(colors.HexColor('#e5e7eb'))
        c.line(20*mm, y - 3*mm, page_width - 20*mm, y - 3*mm)
        y -= 10*mm

    # Footer
    c.setFont('Helvetica', 8)
    c.setFillColor(colors.HexColor('#9ca3af'))
    c.drawString(
        20*mm, 15*mm,
        f'Generated by eSign Platform · {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC'
    )

    c.save()
    buffer.seek(0)
    return buffer


def stamp_signatures_on_pdf(original_file, signature_fields_by_page):
    """
    Overlays recipient signatures onto the original PDF at the exact positions
    defined by SignatureField records.

    signature_fields_by_page: dict of { page_number (1-indexed): [field_dict, ...] }
    Each field_dict must have:
        x, y, width, height  — percentages (0.0–1.0) of page dimensions
        signature_data        — base64-encoded PNG from the recipient

    PDF coordinate origin is bottom-left, but our stored (x, y) uses top-left origin
    (as the browser does). We convert y here: pdf_y = page_height - (y + height) * page_height
    """
    reader = PdfReader(original_file)
    writer = PdfWriter()

    for page_idx, page in enumerate(reader.pages):
        page_number = page_idx + 1  # 1-indexed

        fields = signature_fields_by_page.get(page_number, [])
        if not fields:
            writer.add_page(page)
            continue

        # Get actual page dimensions from the PDF
        media_box = page.mediabox
        page_width = float(media_box.width)
        page_height = float(media_box.height)

        # Build an overlay canvas at the same dimensions as this page
        overlay_buffer = io.BytesIO()
        c = canvas.Canvas(overlay_buffer, pagesize=(page_width, page_height))

        for field in fields:
            sig_data = field.get('signature_data')
            if not sig_data:
                continue

            try:
                # Decode signature image
                raw = sig_data.split(',')[1] if ',' in sig_data else sig_data
                img_bytes = base64.b64decode(raw)
                img = Image.open(io.BytesIO(img_bytes)).convert('RGBA')

                img_buffer = io.BytesIO()
                img.save(img_buffer, format='PNG')
                img_buffer.seek(0)

                # Convert percentage coords → absolute PDF coords
                abs_x = field['x'] * page_width
                abs_w = field['width'] * page_width
                abs_h = field['height'] * page_height

                # Convert top-left y origin → bottom-left PDF origin
                abs_y = page_height - (field['y'] + field['height']) * page_height

                c.drawImage(
                    img_buffer,
                    abs_x, abs_y,
                    width=abs_w,
                    height=abs_h,
                    preserveAspectRatio=True,
                    mask='auto'
                )
            except Exception:
                pass  # Skip fields that can't be rendered; don't fail the whole PDF

        c.save()
        overlay_buffer.seek(0)

        # Merge overlay onto the original page
        overlay_reader = PdfReader(overlay_buffer)
        overlay_page = overlay_reader.pages[0]
        page.merge_page(overlay_page)
        writer.add_page(page)

    output = io.BytesIO()
    writer.write(output)
    output.seek(0)
    return output


def merge_pdf_with_certificate(stamped_pdf, certificate_buffer):
    """
    Appends the certificate page to the (already-stamped) PDF.
    Returns bytes of the merged PDF.
    stamped_pdf can be a file object or BytesIO.
    """
    writer = PdfWriter()

    # Add all original/stamped pages
    reader = PdfReader(stamped_pdf)
    for page in reader.pages:
        writer.add_page(page)

    # Add certificate page(s)
    cert_reader = PdfReader(certificate_buffer)
    for page in cert_reader.pages:
        writer.add_page(page)

    output = io.BytesIO()
    writer.write(output)
    output.seek(0)
    return output


def convert_docx_to_pdf(docx_file_obj):
    """
    Phase 7.31 — DOCX → PDF auto-conversion.
    Converts a DOCX file to PDF using python-docx + reportlab.
    Pure-Python; no LibreOffice required.
    Returns: BytesIO containing the PDF bytes.
    """
    from docx import Document as DocxDocument
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    docx = DocxDocument(docx_file_obj)
    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=A4)
    styles = getSampleStyleSheet()

    heading1_style = ParagraphStyle(
        'H1Custom', parent=styles['Heading1'], fontSize=18, spaceAfter=12,
    )
    heading2_style = ParagraphStyle(
        'H2Custom', parent=styles['Heading2'], fontSize=14, spaceAfter=8,
    )
    body_style = ParagraphStyle(
        'BodyCustom', parent=styles['Normal'], fontSize=11, spaceAfter=6, leading=14,
    )

    story = []
    for para in docx.paragraphs:
        text = para.text.strip()
        if not text:
            story.append(Spacer(1, 6))
            continue
        style_name = para.style.name if para.style else ''
        if 'Heading 1' in style_name:
            style = heading1_style
        elif 'Heading 2' in style_name:
            style = heading2_style
        else:
            style = body_style
        safe_text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        story.append(Paragraph(safe_text, style))

    if not story:
        story.append(Paragraph("(Empty document)", body_style))

    doc.build(story)
    output.seek(0)
    return output


def verify_file_hash(file_obj, expected_hash):
    """
    Phase 7.32 — Post-sign hash re-verification (tamper check).
    Computes the SHA-256 of a file and compares it to the stored hash.
    Returns: (bool match, str computed_hash)
    """
    import hashlib
    sha256 = hashlib.sha256()
    file_obj.seek(0)
    for chunk in iter(lambda: file_obj.read(8192), b''):
        sha256.update(chunk)
    computed = sha256.hexdigest()
    return (computed == expected_hash), computed
