# Generated by Django 6.0.5 on 2026-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
