# Generated by Django 6.0.5 on 2026-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_recipient_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='signed_file',
            field=models.FileField(blank=True, help_text='Generated signed PDF after all parties have signed', null=True, upload_to='signed_documents/'),
        ),
    ]
