# Generated by Django 6.0.5 on 2026-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_add_cancelled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
