# Generated by Django 6.0.5 on 2026-06-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='reminder_days',
            field=models.PositiveIntegerField(default=0, help_text='Send reminders every N days. 0 disables reminders.'),
        ),
    ]
