# Generated by Django 6.0.5 on 2026-06-03 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_add_reminder_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipient',
            name='delegated_to',
            field=models.ForeignKey(blank=True, help_text='If this recipient delegated their signing, points to the new recipient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_from', to='packages.recipient'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('DELEGATED', 'Delegated'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='1-indexed page number in the PDF')),
                ('x', models.FloatField(help_text='Left edge as fraction of page width')),
                ('y', models.FloatField(help_text='Top edge as fraction of page height')),
                ('width', models.FloatField(default=0.2, help_text='Width as fraction of page width')),
                ('height', models.FloatField(default=0.07, help_text='Height as fraction of page height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='packages.package')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='packages.recipient')),
            ],
            options={
                'ordering': ['page_number', 'y', 'x'],
            },
        ),
    ]
